import './globals.css'

export const metadata = {
  title: 'Kim Da-mi',
  description: 'Generated by create next app',
  icons: {
    icon: 'https://i.pinimg.com/564x/d5/9d/6e/d59d6e86c152c947eab8281e011d3cf2.jpg',
  },
  openGraph: {
    images: 'https://i.pinimg.com/564x/d5/9d/6e/d59d6e86c152c947eab8281e011d3cf2.jpg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}